### ISSUE TITLE
Segmentation fault in RAND_bytes()

### ISSUE THREAD

**Issue by atifismail** [libssh2/libssh2#217]
**I have singleton class using libcurl for sftp file upload and I and getting segmentation fault in libssh2_session_handshake(), please help, here is the stack,**

#0  0x0000000000aa89a8 in RAND_bytes ()
#1  0x0000003ca540be9c in kexinit (session=0x7f728402e390, reexchange=<value optimized out>, key_state=0x7f728403b038) at kex.c:1074
#2  _libssh2_kex_exchange (session=0x7f728402e390, reexchange=<value optimized out>, key_state=0x7f728403b038) at kex.c:1705
#3  0x0000003ca5412c37 in session_startup (session=0x7f728402e390, sock=37) at session.c:718
#4  libssh2_session_handshake (session=0x7f728402e390, sock=37) at session.c:796
#5  0x0000003cb103c8f3 in ?? () from /usr/lib64/libcurl.so.4
#6  0x0000003cb103f8f5 in ?? () from /usr/lib64/libcurl.so.4
#7  0x0000003cb103fd7b in ?? () from /usr/lib64/libcurl.so.4
#8  0x0000003cb101e362 in Curl_protocol_connect () from /usr/lib64/libcurl.so.4
#9  0x0000003cb10248f5 in Curl_connect () from /usr/lib64/libcurl.so.4
#10 0x0000003cb102c930 in Curl_perform () from /usr/lib64/libcurl.so.4
#11 0x00000000005bf4fb in SFtpClient::write (this=0x7f7284010370, filePath="crl/crl1p1dp1.crl", bsData=<incomplete type>) at SFtpClient.cpp:110
.
.
.
#23 ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::handle_events (this=0x7f7284002a00, max_wait_time=0x7f728bc4cce0)
    at ACE_wrappers/ace/Select_Reactor_T.cpp:1441
#24 0x000000000054d438 in handle_events (this=0xfb0900) at ACE_wrappers/ace/Reactor.inl:188
#25 CConnectionHandler::svc (this=0xfb0900) at ConnectionHandler.cpp:252
#26 0x00007f72927d6477 in ACE_Task_Base::svc_run (args=0xfb0900) at Task.cpp:271
#27 0x00007f72927d7a55 in ACE_Thread_Adapter::invoke_i (this=<value optimized out>) at Thread_Adapter.cpp:161
#28 0x00007f72927d7ad1 in ACE_Thread_Adapter::invoke (this=0xfb24f0) at Thread_Adapter.cpp:96
#29 0x0000003c9ac07aa1 in start_thread (arg=0x7f728bc4d700) at pthread_create.c:301
#30 0x0000003c9a8e8bcd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115

------------------------------------------
**I am using Centos 6, here is source code**

```
struct upload_data
{
  char *memory;
  size_t len;
};

static size_t read_callback(void *ptr, size_t size, size_t nmemb, void *stream)
{
	struct upload_data *userdata = (struct upload_data *)stream;
	size_t curl_size = nmemb * size;
	size_t to_copy = (userdata->len < curl_size) ? userdata->len : curl_size;
	memcpy(ptr, userdata->memory, to_copy);
	userdata->len -= to_copy;
	userdata->memory += to_copy;
	return to_copy;
}

SFtpClient::SFtpClient(void)
{
	curl = NULL;
	init();
}

SFtpClient::~SFtpClient(void)
{
	curl_easy_cleanup(curl);
	curl_global_cleanup();
}

int SFtpClient::init()
{
	CURLcode res;
	res = curl_global_init(CURL_GLOBAL_ALL);
	curl = curl_easy_init();
	if(curl) {	
		curl_easy_setopt(curl, CURLOPT_READFUNCTION, read_callback);
		curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);		
		std::string userPwd =  CFGSingleton::Instance().getSftpUserName() + ":" + CFGSingleton::Instance().getSftpPassword();
		curl_easy_setopt(curl, CURLOPT_USERPWD, strdup(userPwd.c_str()));		
	}
	else
	{
		curl = NULL;		
		m_strErrMsg = "Failed to initialize libcurl : ";
		m_strErrMsg += curl_easy_strerror(res);
	}

	return res;
}

int SFtpClient::write(std::string filePath, ByteString bsData)
{	
	CURLcode res;
	struct upload_data userdata;
	userdata.memory = (char*) bsData.getBuffer();
	userdata.len = bsData.getLength();
	if(!curl)
		init();

	if(curl) {		
		std::string remoteFilePath = "sftp://";
		remoteFilePath += strdup(CFGSingleton::Instance().getHttpServerIP().c_str());
		remoteFilePath += ":";
		char pszPort[10] = {0};
		sprintf(pszPort,"%d",CFGSingleton::Instance().getHttpServerPort(),pszPort);
		remoteFilePath += pszPort;
		remoteFilePath += "/";
		remoteFilePath += filePath;

		curl_easy_setopt(curl, CURLOPT_URL, strdup(remoteFilePath.c_str()));	
		curl_easy_setopt(curl, CURLOPT_READDATA, (void*)&userdata);
		curl_easy_setopt(curl, CURLOPT_INFILESIZE_LARGE, (curl_off_t)bsData.getLength());

		res = curl_easy_perform(curl);

		if(res != CURLE_OK)
			m_strErrMsg = "curl_easy_perform() failed: ";
			m_strErrMsg = curl_easy_strerror(res);
	}
	return res;
}
```

**Comment by atifismail** [comment]
Sorry guys I was my fault. Turn out it was symbol colliding problem with some other library.
