### ISSUE TITLE
libssh2_channel_close() blocks

### ISSUE THREAD

**Issue by colinw-smartrg** [libssh2/libssh2#232]
Running libssh2 1.8.0 on Linux in OpenWRT.

Our application uses libssh2 in a non-blocking mode to do remote execution of scripts. 
On occasion, after setting up the connection and channel, the call to
libssh2_channel_read( phost->channel, buf, len );
will return some data, then the subsequent call returns LIBSSH2_ERROR_EAGAIN, then
libssh2_session_block_directions( phost->session );
Returns LIBSSH2_SESSION_BLOCK_INBOUND.

The socket is added to our poll() loop with events set to POLLIN, but it does not gets another returned event. After a 10 second timeout, we decide the execution has failed and call libssh2_channel_close() in the following loop:
while( libssh2_channel_close( phost->channel ) == LIBSSH2_ERROR_EAGAIN );

This never returns.
The backtrace usually shows:

#0  0x36e2979c in gettimeofday () from /lib/libc.so.6
#1  0x36e2976c in time () from /lib/libc.so.6
#2  0x36f13a54 in libssh2_channel_close () from /usr/lib/libssh2.so.1

But also shows:
#0  0x36e6f540 in recv () from /lib/libc.so.6
#1  0x36f12af0 in _libssh2_recv (sock=9, buffer=0x908e4, length=16384, flags=16384, abstract=0x907a8) at misc.c:128
#2  0x36f2a814 in _libssh2_transport_read (session=0x907a8) at transport.c:368
#3  0x36f09750 in _libssh2_channel_close (channel=0x40b48) at channel.c:2351
#4  0x36f09830 in libssh2_channel_close (channel=0x40b48) at channel.c:2385

Most of the time we don't have this issue, but it is relatively easy to reproduce.
Seems like the script that is running on the remote is just taking longer than the expected 10 seconds.
However, we need it to not block if we want to close the channel before it is complete.

Same exact problem in version 1.6.0.

**Comment by colinw-smartrg** [comment]
This appears to be an issue with waiting for the remote SSH_MSG_CHANNEL_CLOSE
It appears the remote sometimes goes away and never sends this, and the socket never seems to see the disconnection.
A work around is to loop only N times and then if still returning LIBSSH2_ERROR_EAGAIN, close the socket before calling close again. This appears to allow for the channel and session to be free'd properly.
